service: poserServer
provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, 'ap-northeast-2'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'
functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          method: any
          path: /
