service: powerServer
provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, 'ap-northeast-2'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: '*'
functions:
  powerServer:
    handler: main.handler
    events:
      - http:
          method: any
          path: https://emt7ymwoci.execute-api.ap-northeast-2.amazonaws.com/default/powerServer
