service: newServer



plugins:
  - serverless-plugin-typescript
  - serverless-plugin-warmup
  - serverless-offline


provider:
  name: aws
  runtime: nodejs16.x
  region: ${opt:region, 'ap-northeast-2'}

functions:
  newServer:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /

