name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            npm install
            npm i -g @nestjs/cli  
            npm ls
            
      - name: Build and zip project
        run: |
          npm run build
          npm prune --production
          cp .env dist/
          cd dist && zip -r ../powerServer.zip * -x "*.git*"

      - name: Deploy to AWS Lambda
        run: |
          ls
          aws lambda update-function-code --region ap-northeast-2 --function-name powerServer --zip-file fileb://powerServer.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
