name: Deploy to AWS Lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        run: |
          npm install
          npm install -g @nestjs/cli
          
      - name: Build application
        run: npm run build
        
      - name: Archive application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.1
        with:
          function-name: powerServer
          handler-name: main.handler
          runtime: nodejs16.x
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          artifact-name: app
