name: deploy-to-aws-lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: AWS Configure
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-2
          
      - name: Deploy to AWS Lambda
        run: |
          npm install
          npm install -g @nestjs/cli
          npm run build
          npm install -g serverless
          aws lambda list-functions
          serverless doctor
          serverless --version
          serverless deploy
          npx sls deploy function -f powerServer



